//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oto_Galeri_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKIRA
    {
        public int Kira_ID { get; set; }
        public Nullable<decimal> Kira_Ucreti { get; set; }
        public Nullable<int> Kira_Gun { get; set; }
        public Nullable<System.DateTime> Kira_AlimTarihi { get; set; }
        public Nullable<System.DateTime> Kira_TeslimTarihi { get; set; }
        public Nullable<decimal> Kira_Tutar { get; set; }
        public int Musteri_ID { get; set; }
        public int Arac_ID { get; set; }
        public int Personel_ID { get; set; }
    
        public virtual TBLARAC TBLARAC { get; set; }
        public virtual TBLMUSTERI TBLMUSTERI { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
